apps/docs/docs/components/info-banner.mdx
apps/docs/docusaurus.config.ts
packages/info-banner/src/lib/InfoBanner.tsx

Stoppade tillbaka propfilter på förekommen anledning. Kan ta den diskussionen och finlira på den om det behövs i annan ticket. Funderar på att commita några andra grejer till denna för tydligare exempel också men kör PR för att bekräfta att det inte är strul med API på gh-pages

docs: update API for InfoBanner

---

apps/docs/src/components/getComponentMetaData.tsx

we're not providing a changelog per component anymore, this button is unnessecary

refactor(docs): remove version log link on component pages

---

packages/components/package.json

gör sig av med den här lilla rackaren: 
typningen verkar dock fungera oavsett 🤷‍♂️

fix(theme): point to theme types

---

apps/docs/docs/components/modal.mdx
apps/docs/docs/components/textarea.mdx
packages/components/src/textarea/TextArea.spec.tsx
packages/components/src/textarea/TextArea.stories.tsx
packages/components/src/textarea/TextArea.tsx
packages/components/src/textfield/TextField.stories.tsx
packages/components/src/textfield/TextField.tsx

breaking change för `TextArea` och `TextField`, byter ut propertyn `maxCharacters` mot `maxLength` enligt motsvarande attributnamn för HTML `<input>` och `<textarea>`
uppdatera validering för `minLength`-attributet
skriv tester för `maxLength`, `minLength`, `isRequired` och custom `validate`-funktioner

feat!/textarea & textfield validation

---

packages/components/src/textarea/TextArea.spec.tsx
packages/components/src/textarea/TextArea.tsx
packages/components/src/textfield/TextField.spec.tsx
packages/components/src/textfield/TextField.tsx

`TextField` and `TextArea` counter value shows `0` if the default `value` or `defaultValue` property is used
Add tests, set the initialValue for `useState` in both components
Test case described in ticket

fix(textfield): set the initial value for useState 

---

packages/components/.storybook/main.ts
packages/components/src/file-upload/FileUpload.spec.tsx
packages/components/src/file-upload/FileUpload.tsx

FileUpload exposed some props that we didn't handle
Create a test for the unhandled prop `onSelect`
Pass the unhandled props to the `FileTrigger` component
Add the correct type for the `handleDrop` callback
Update the docgen config for storybook to match the same props as docusarus
The `acceptedFileTypes` prop is easiest to test manually

fix(file-upload): pass unhandled props to the FileTrigger component

---

nx.json

Tar bort lite clutter från framtida changelogs för chore-commits. Alltid work in progress men jag tror det här är vettigt, input?
Lägger även docs under egen rubrik samt undantaget för version bumps

chore: ignore chore commits in changelog, no version bump for docs

---

packages/components/package.json

Our npm package has no explicit export for the global css file
Add the export to package.json
tested locally using `nx build components` -> `npm pack` -> `npm i ...`

fix(theme): add global css export

---

.github/workflows/components-ci.yml
.github/workflows/documentation-ci.yml
.github/workflows/documentation-pr.yml
.github/workflows/publish.yml
apps/docs/docs/get-started/contribute.mdx
package-lock.json
package.json

Bump to Node v22 in GH Actions and codebase
- Changed to node 22 in all gh actions
- Added NPM cache on some gh actions where it was lacking
- Codebase now demands node 22 or higher
- Changed get started docs
All must upgrade to node to at least 22 or run nvm
- [] Tests added if applicable

chore: bump to node 22

---

packages/components/src/radio/Radio.module.css

Fixes issue from support where RadioGroup renders incorrectly in some situations.
1. Remove `height: 100%` on RadioGroup
2. Set correct hover background in mobile view

fix(radio): fix hover on mobile, remove 100% height on RadioGroup

---

packages/components/src/search-field/SearchField.module.css
packages/components/src/search-field/SearchField.spec.tsx
packages/components/src/search-field/SearchField.stories.tsx
packages/components/src/search-field/SearchField.tsx
packages/components/src/search-field/index.ts

The validation for SearchField was different if the user used the mouse or the keyboard to submit
* Add tests
* Style the validation error text
* Use `useSearchField` hook to get the button to submit
* Drop support for `isRequired` prop
* Change some styling for the input (!!)
I couldn't get the `isRequired` prop to validate without wrapping the SearchField with a form

fix(search-field): validation text

---

packages/components/src/card/Card.spec.tsx
packages/components/src/card/Card.tsx

Card css breaks when using the `className` prop
Add a test
Break out the className prop

fix(card): append props.className

---

packages/components/src/checkbox/Checkbox.module.css
packages/components/src/date-picker/DatePicker.module.css
packages/components/src/radio/Radio.module.css

Sets `cursor: pointer` on interactive elements, `cursor: not-allowed` on disabled elements
Fixes #299 (Select will be in separate issue)

fix: set correct cursor for radio, checkbox, datepicker

---

packages/components/src/date-picker/DatePicker.tsx

change the weekday names to swedish languge
add prop weekdayStyle='short' in CalendarGrid

fix: change the weekday names to swedish languge

---

packages/components/src/button/Button.module.css

Primary button looks the same as other buttons. This increases border width for primary
When `forced-colors: active` -> `border-width: 2px` on primary btn

feat(button): set primary border to 2px when in high-contrast mode

---

packages/components/src/date-picker/DatePicker.module.css
packages/components/src/date-picker/DatePicker.tsx

Datepicker invalid border hides button. Button is too large to fit with border on the wrapper
Change button height and move to the left when in invalid state

fix(date-picker): resize button in invalid state, fixes #312

---

packages/components/src/select/Select.module.css
packages/components/src/select/Select.tsx
packages/components/src/select/SelectListBox.tsx

Selecting elements directly causes css to bleed out of component scope (in Storybook etc.)
Add a class to checkbox inputs
Select the class instead of the input in the css file

fix(select): change direct element selector

---

.github/workflows/test-storybook.yml
README.md
packages/components/src/checkbox/Checkbox.stories.tsx
packages/components/src/combobox/ComboBox.stories.tsx
packages/components/src/date-picker/DatePicker.stories.tsx
packages/components/src/file-upload/FileUpload.stories.tsx
packages/components/src/radio/Radio.stories.tsx
packages/components/src/textarea/TextArea.stories.tsx
packages/components/src/textfield/TextField.stories.tsx

Since we started using Storybook play functions some stories don't make sense to show in the sidebar
(Stories wrapped in ugly forms just to test form validation etc.)
Hide some stories using the `"!dev"`-tag
Add a badge to README
The test runner will run tests on the stories even if they're hidden. If you need to debug tests using the UI you can temporarily remove the tag.

test(components): ✅ Remove test stories from sidebar

---

package-lock.json
package.json
packages/components/package.json
packages/components/src/toast/Toast.module.css
packages/components/src/toast/Toast.tsx

I wanted to do this later, but I'm blocked locally without these edits.
Update `react-aria-components` and `react-stately`
Remove explicit dependencies to `@react-aria/toast` (no need anymore)
Add temporary bug free implementation of [useToastState](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/toast/src/useToastState.ts#L59)
Due to the new animation approach animations will fail if you try them on the Storybook Docs page. This is because of duplicate regions. But I guess it's a corner case we should not support?

chore: update react-aria-components

---

packages/components/src/link-button/LinkButton.module.css

Fix bug with dark mode tokens on LinkButton hover states
Prevented that hover text is sometimes white.

fix(link-button): fix colors on hover state

---

.github/workflows/publish.yml

Only change to publish file since last successful publish, testing to see if this solves the problem. **CONFIRMED WORKING!**
- remove node_env setting in publish workflow

chore: revert node_env in publish.yml

---

packages/components/src/accordion/Accordion.module.css
packages/components/src/button/Button.module.css
packages/components/src/button/Button.stories.tsx
packages/components/src/card/Card.module.css
packages/components/src/checkbox/Checkbox.module.css
packages/components/src/combobox/ComboBox.module.css
packages/components/src/dropdown/Dropdown.module.css
packages/components/src/dropdown/Dropdown.tsx
packages/components/src/file-upload/FileUpload.module.css
packages/components/src/file-upload/FileUpload.stories.tsx
packages/components/src/layout/Layout.module.css
packages/components/src/link-button/LinkButton.module.css
packages/components/src/link-button/LinkButton.stories.tsx
packages/components/src/link/Link.module.css
packages/components/src/radio/Radio.module.css
packages/components/src/search-field/SearchField.module.css
packages/components/src/search-field/SearchField.tsx
packages/components/src/tag/Tag.module.css
packages/components/src/textfield/TextField.module.css

For **building high quality interactions** we should use React Aria's data-attributes instead of native pseudo-classes when possible
Replace pseudo-classes found in components
UX approves my deletion in `Card.module.css`

chore(components): 💄replace pseudo-class selectors

---

packages/components/src/link-button/LinkButton.module.css
packages/components/src/link/Link.module.css

In first page in Docs webb the link buttons pseudo-classes not working
Add pseudo-classes to primary and secondary buttons in css link button 

fix(link-button): add pseudo-classes in CSS link-button to primary and secondary

---

packages/components/src/textfield/TextField.module.css

Fixes support ticket about dark mode on textfield
Added token to textfield input
Change to dark mode and enter something in TextField, the input should be white

fix(textfield): fix token on input value

---

apps/docs/docs/components/tabs.mdx
packages/components/src/tabs/Tabs.module.css

- Fix tab title in dark mode
- Add better example on docweb with typography components

fix(tabs): fix dark mode on tabs and example on docweb

---

apps/docs/docs/components/button.mdx
apps/docs/docs/components/calendar.mdx
apps/docs/docs/components/checkbox.mdx
apps/docs/docs/components/combobox.mdx
apps/docs/docs/components/link-button.mdx
apps/docs/docs/components/link.mdx
apps/docs/docs/components/radio.mdx
apps/docs/docs/components/skeleton.mdx
apps/docs/docs/components/spinner.mdx
apps/docs/docs/components/textarea.mdx
apps/docs/docs/components/textfield.mdx
apps/docs/docs/design-patterns/buttons-and-links.mdx
apps/docs/docs/design-patterns/page-loading.mdx
apps/docs/docs/design-patterns/personnummer.mdx
apps/docs/docs/dev/client-side-routing.mdx
apps/docs/docs/dev/common-issues.mdx
apps/docs/docs/dev/localization.mdx
apps/docs/docs/get-started/contribute.mdx
apps/docs/docs/get-started/use.mdx
apps/docs/src/css/custom.css
apps/docs/static/files/CHANGELOG.md

Links in the documentation has different styling and doesn't meet WCAG color contrast requirements
* Change color of markdown links `[i am a markdown link](//google.com)`
* Replace markdown links with `<Link>` component

docs: ♿️💄 sync markdown links

---

apps/docs/docs/components/modal.mdx
apps/docs/src/components/examples/ModalExamples.tsx
apps/docs/tsconfig.json

We need better examples of modal content
* Add example with form elements
* Add confirmation modal example
* Add react-jsx support to docs typescript compiler (so you dont have to import react to write JSX)

docs(modal): 📝 add examples with form elements

---

packages/components/src/layout/Layout.module.css
packages/components/src/link/Link.module.css
packages/components/src/modal/Dialog.module.css
packages/components/src/select/Select.module.css
packages/components/src/textfield/TextField.module.css
packages/components/src/theme/tokens.css
packages/components/src/theme/tokens.ts
packages/components/src/toast/Toast.module.css

Select popover is stacked under modal overlay, we need semantic z-index tokens to prevent bugs like these
* Change z-index of modal overlay
* Export semantic z-index tokens
* Use tokens
Starting at 1000 with the modal overlay to render stuff above docusarus UI (0 - 400).

feat: ✨💄 add semantic z-index tokens

---

packages/components/src/combobox/ComboBox.module.css
packages/components/src/date-field/DateField.module.css
packages/components/src/date-picker/DatePicker.module.css
packages/components/src/textfield/TextField.module.css
packages/components/src/theme/tokens.css

Our error message doesn't meet WCAG contrast ratio in dark mode
* Implement `@value --signal-red-120: #eb4e4e;`
* Replace `--border-invalid` and `--text-invalid` in dark mode
* Remove some unused css imports
Currently we're not catching WCAG violations in dark mode with the test runner, something to look into!

fix: ♿️🐛 error message color in dark mode

---

.github/workflows/test-storybook.yml
packages/components/.storybook/test-runner.ts
packages/components/jest.config.ts
packages/components/project.json
packages/components/src/card/Card.stories.tsx
packages/components/src/flex/Flex.stories.tsx
packages/components/src/grid/Grid.stories.tsx
packages/components/src/table/Table.stories.tsx
packages/components/src/utils/test.ts
packages/components/tsconfig.storybook.json

We're not running automated tests for storybook dark mode
* Emulate media for "prefers-color-scheme" in test runner config
* Bypass failing tests
Some a11y violations in dark mode. If we merge this I will create issues for all occurencies of `test: 'todo'`

test: ✅ storybook tests for dark mode

---

.github/workflows/release.yml

🏎️ Remove the need for manually triggering release, instead every push to main should trigger nx release.
⛑️ Add workflow file release.yml
This PR has base **main** which I consider to be correct. We fix this issue separate from the dev and feature branches. Testing for errors is quite hard with this one but release can still be done manually + fingers crossed automation will work🤞 (since it's untested, please double check for any smelly code here when PR:ing!)

chore: add workflow to trigger nx release on push to main 🏗️ 

---

packages/components/.storybook/preview.tsx
packages/components/src/calendar/Calendar.stories.tsx
packages/components/src/layout/Layout.stories.tsx

TL:DR; Calendar component had a11y violations
The `<header>` element used in `Calendar` got infered `role=banner` due to missing landmark in the context. Placing the Calendar inside of a `main` or `aside` or whatever landmark fixes this and makes the role `sectionHeader` which is valid.
This PR proposes a default main landmark to render components inside, if needed stories can be configured with:
```js
parameters: {
rootElement: 'div' 
}
```
* Add default main element for stories
* Remove a11y test-todo
* Override main element for `Layout` stories

test: ✅♿️ add default main landmark to storybook

---

apps/docs/docs/design-patterns/forms.mdx
apps/docs/docusaurus.config.ts
apps/docs/static/files/CHANGELOG.md

Explain to our users how to use the `errorPosition` property on form elements
* add documentation exampe
* remove live code block
* adjust the other examples to better fit different screen sizes (the text mass made the layout look funky)

docs: 📝 add example for errorPosition property

---

packages/components/src/checkbox/CheckboxGroup.tsx
packages/components/src/combobox/ComboBox.tsx
packages/components/src/date-field/DateField.tsx
packages/components/src/date-picker/DatePicker.tsx
packages/components/src/field-error/FieldError.tsx
packages/components/src/radio/Radio.tsx
packages/components/src/search-field/SearchField.tsx
packages/components/src/select/Select.tsx
packages/components/src/textfield/TextFieldBase.tsx

Definition of types `ErrorPosition` and `ErrorMessage` wasn't visible in docs prop table
Define types at  component level

docs:📝define ErrorPosition and ErrorMessage at component level

---

apps/docs/docs/components/accordion.mdx
packages/components/src/accordion/Accordion.module.css
packages/components/src/accordion/Accordion.stories.tsx
packages/components/src/accordion/Accordion.tsx
packages/components/src/accordion/AccordionItem.tsx

- fixes responsive bug and uses css for animations (chrome only)
- remove useEffect
- add calc-size for height of panel

fix(accordion): fix responsive content hiding when changing screen size

---

apps/docs/docs/components/select.mdx
apps/docs/src/components/examples/select/SelectExamples.tsx
packages/components/src/select/HiddenMultiSelect.tsx
packages/components/src/select/Select.spec.tsx
packages/components/src/select/Select.stories.tsx
packages/components/src/select/Select.tsx
packages/components/src/select/useMultiSelectState.ts

TL:DR; Documentation and refactoring, always get back `Selection` in controlled mode, for both `single` and `multiple` mode.
When writing documentation for controlled mode I realised the signature of `selectedKeys` and `onSelectionChange` differed:
`selectedKeys`: `"all" | Iterable<Key> | undefined`
`onSelectionChange`: `'all' | Set<Key> | Key | Key[]`
This PR proposes the same state, default values and return value from `onSelectionChange` for both `single` and `multiple` mode:
`selectedKeys?`: `"all" | Iterable<Key>`
`defaultSelectedKeys?`: `"all" | Iterable<Key>`
`onSelectionChange`: `Selection | undefined`
Usage would be:
`selectedKeys` = `new Set(['kiwi'])` or `new Set(['kiwi', 'banana'])`
`handleChange` = `(value?: Selection) => setSelectedKeys(value)` or if you will: `handleChange` …

refactor(select): 📝♻️

---

apps/docs/docs/components/radio.mdx
apps/docs/src/components/examples/radio/RadioExamples.tsx
packages/components/src/radio/Radio.module.css
packages/components/src/radio/Radio.stories.tsx

Add missing support for horizontal orientation on radiogroup.
Update docs to exemplify that we use max 2 radio options

fix(radio): add support for horizontal orientation

---

apps/docs/docs/components/calendar.mdx
packages/components/src/calendar/Calendar.module.css
packages/components/src/calendar/Calendar.tsx
packages/components/src/calendar/RangeCalendar.tsx

It's hard to see what's calendar and what's not in high contrast mode
- add border for high contrast mode
Remove the calendar class from the table, looked like it did nothing there

fix(calendar): ♿️ add border for high contrast mode

---

apps/docs/docs/dev/dark-mode.mdx

- Copied global.css instructions from /get-started/use to dark-mode page
- Purposely "disabled" ColorSchemeSwitch on docweb, we just need to show how it looks.

docs: clarify use of global.css and disable switch functionality

---

packages/components/src/modal/Dialog.tsx

Text in modal body was not selectable by normal mouse action. This fixes that issue
- add `tabIndex={-1}` to modalbody

fix(modal): make text in modal selectable

---

packages/components/src/checkbox/Checkbox.module.css

the text in checkbox is difficult to see in high contrast mode(dark theme)
line-height is missing in checkbox
_issue number: DS-1038_ and _DS-1056_
Add to the color activeText in high contrast mode 
Add line height to checkbox

fix(checkbox): add in hight contrast the color activeText

---

packages/components/src/accordion/Accordion.module.css
packages/components/src/accordion/Accordion.stories.tsx
packages/components/src/utils/test.ts

Using disabled children inside Accordion caused the Accordion to look disabled
- Remove the CSS :has pseudo class

fix(accordion): 🐛 remove disabled styling if component has disabled children

---

apps/docs/docs/components/radio.mdx

We no longer want to recommend our users to always have one radio button selected by default. 
Removed the guideline
Guidance regarding when to have a radio button selected by default will be added later

:memo: :fire: Remove a radio button guideline

---

packages/components/src/label/Label.module.css
packages/components/src/label/Label.stories.tsx
packages/components/src/label/Label.tsx

Label component has two varinats but just one is used.
_Issue number: DS-1033_
deprecate variant and add label class

feat(label): deprecate variant and add label class

---

package-lock.json
package.json
packages/components/.eslintrc.json
packages/components/src/accordion/Accordion.tsx
packages/components/src/button/Button.tsx
packages/components/src/card/Card.tsx
packages/components/src/label/Label.tsx
packages/components/src/modal/Dialog.tsx
packages/components/src/spinner/Spinner.tsx
packages/components/src/table/Table.tsx
packages/components/src/tabs/Tabs.tsx
packages/components/src/utils/intl/useMessageFormatter.ts
tools/eslint/handle-deprecated-comments.js
tools/eslint/handle-deprecated-comments.test.js
tools/eslint/index.js
tools/eslint/package.json

We should batch remove our deprecated features to minimize major version bumps
Add two different warnings
The only backside is that we have to manually edit the eslint-config with our version number to get this to work. If we used the eslint flat config we could read package.json.config

chore: add a specific eslint rule for '@deprecated' comments

---

apps/docs/docs/components/textfield.mdx
apps/playground/src/app/app.tsx
packages/components/src/textfield/TextField.module.css
packages/components/src/textfield/TextField.stories.tsx
packages/components/src/textfield/TextFieldBase.tsx
packages/components/src/theme/tokens.css

New setting for textfield to make it smaller
- add size prop and set padding to correct size

feat(textfield): add medium size option to input padding

---

packages/components/src/textfield/TextArea.stories.tsx
packages/components/src/textfield/TextArea.tsx
packages/components/src/textfield/TextField.stories.tsx
packages/components/src/textfield/TextField.tsx

Native dom-egenskaper saknas på TextArea och TextField, komponenterna kan inte användas på samma sätt som HTMLs `<textarea>` och `<input>`. Som exempel accepteras inte autocapitalize, cols, dirname, form, placeholder, rows, wrap för `Textarea`.
- Utöka våra interfaces med relevanta och användbara props och passa dem manuellt till respektive komponent
attributen `dir` och `dirName` verkar hanteras dåligt av react-aria respektive @types/react, om vi någonsin behöver dem får vi kika vidare på det

fix(textfield): merge textfield and input/textarea native dom props

---

packages/components/.storybook/preview.tsx
packages/components/src/calendar/RangeCalendar.stories.tsx
packages/components/src/utils/storybook.ts

We get visual diffs in chromatic because the date changes in our components
- Mock dates in every story

chore: 🤡 mock dates globally in storybook

---

.github/workflows/documentation-pr.yml
apps/docs/docusaurus.config.ts
apps/docs/jest.config.js
apps/docs/project.json
apps/docs/src/utils/chromatic.test.ts
apps/docs/src/utils/chromatic.ts

chromatic doesnt allow all characters in branch names
- add test foundation for docs
- replace underscores, multiple dashes and slashes with a single dash in chromatic branch url

fix: 🐛 replace special characters in chromatic branch names

---

apps/docs/src/css/custom.css

Removes max-height constraint from card-guidelines which is used on the language page
Removed `max-height`
The constraint works fine for our component pages but isn't neccessary on the language page, it just looks wierd that you have to scroll an example

chore: ⬇️ remove max-height from card-guidelines

---

packages/components/src/calendar/Calendar.module.css
packages/components/src/calendar/Calendar.stories.tsx

Reported by a fellow co-worker in the support channel
- Apply `cursor: not-allowed;` to disabled dates.

fix(calendar): 🐛 add cursor: not-allowed on disabled dates

---

apps/docs/src/components/PropsTable.tsx
apps/docs/src/utils/jsdocLinkToMarkdown.ts

jsdoc links was not rendered as links in component api.
Button has a field for Icon with a link to Lucide. This should now be a valid markdown link

docs: render jsdoc links as markdown in component api description field

---

packages/components/.eslintrc.json
packages/components/src/skeleton/Skeleton.stories.tsx
packages/components/src/skeleton/Skeleton.tsx
tools/eslint/handle-deprecated-comments.js
tools/eslint/handle-deprecated-comments.test.js

Reported by a fellow co worker in the support channel
`Skeleton` accepts `className` and `style` (among others) but it gets overwritten.
- chore: update eslint rule to handle major versions > 9
- fix(skeleton): dont overwrite className and style props

fix(skeleton): dont overwrite properties

---

.commitlintrc.js
package-lock.json
package.json

Allows exclamation marks in commit subject for breaking changes
`feat!: a breaking change`
`feat(accordion)!: a breaking change` 
etc,
- extend commitlint conventional commits config

chore: extend commitlint conventional commits config

---

packages/components/src/link-button/LinkButton.module.css
packages/components/src/link-button/LinkButton.stories.tsx

Support ticket
- add `cursor: not-allowed` to disabled `LinkButton`s
- add consistent disabled styling to `LinkButton` variations

fix(link-button): add disabled styling

---

apps/docs/src/components/PropsTable.tsx

Har att göra med att vi nu sätter bakgrund på Accordions och glitch mellan Docusaurus lösning med [data-theme=""] i HTML och vår lösning med color-scheme i CSS. 
- Stäng av bakgrund på Accordion på PropsTable, onödigt där

docs: no bg on proptable accordions

---

apps/docs/docs/components/table.mdx
apps/docs/src/components/examples/table/TableExamples.tsx
apps/docs/src/css/custom.css
packages/components/src/table/Table.module.css
packages/components/src/table/Table.stories.tsx
packages/components/src/table/Table.tsx

Medium size for `Table`
- feat(table): add size prop
- style(table): adjust paddings and heights
- test(table): test medium size prop
- docs(table): update docs on medium size
Found some deviations from the Figma figma spec!
Updates the font size and paddings
- sort the CSS
- use token values
- get rid of DOM element selectors like `th` and `td` in favor of `.cell` and `.column` etc.
- nest some selectors
- update the styling for `narrow` even if its deprecated.

feature(table): medium size

---

packages/components/src/textfield/TextField.module.css
packages/components/src/textfield/TextField.stories.tsx

Fixes #642 
TextField pushes content in wrappers
- remove `height:100%` on wrapper

fix(textfield): remove `height:100%` on wrapper

---

.gitignore
packages/components/.storybook/examples/SearchField.stories.tsx
packages/components/project.json

A little typescript error in a search field example story
- chore(search-field): add column id type to story
- chore(components): add command to watch for typescript errors
run `nx compile components` to watch for typescript errors

chore(components): add command to watch for typescript errors

---

apps/docs/changelog/source/1.0.1.md
apps/docs/changelog/source/1.0.2.md
apps/docs/changelog/source/1.1.0.md
apps/docs/changelog/source/1.2.0.md
apps/docs/changelog/source/1.3.0.md
apps/docs/changelog/source/10.0.0.md
apps/docs/changelog/source/10.1.0.md
apps/docs/changelog/source/10.1.1.md
apps/docs/changelog/source/10.2.0.md
apps/docs/changelog/source/2.0.0.md
apps/docs/changelog/source/2.0.1.md
apps/docs/changelog/source/3.0.0.md
apps/docs/changelog/source/3.1.0.md
apps/docs/changelog/source/4.0.0.md
apps/docs/changelog/source/5.0.0.md
apps/docs/changelog/source/5.0.1.md
apps/docs/changelog/source/6.0.0.md
apps/docs/changelog/source/6.0.1.md
apps/docs/changelog/source/6.1.0.md
apps/docs/changelog/source/6.2.0.md
apps/docs/changelog/source/7.0.0.md
apps/docs/changelog/source/7.1.0.md
apps/docs/changelog/source/8.0.0.md
apps/docs/changelog/source/8.1.0.md
apps/docs/changelog/source/8.2.0.md
apps/docs/changelog/source/8.3.0.md
apps/docs/changelog/source/9.0.0.md
apps/docs/src/plugins/changelog/index.ts

Update the changelog autoformatting that happens when we build or serve the docs app.
This will align with our prettier config, so editing/formatting a file shouldnt cause any diffs.
- Add a newline at the end of each entry
- Add a space before the frontmatter "format: md"
- Convert all h3:s to h2:s

docs: edit changelog autoformatting

---

packages/components/src/combobox/ComboBox.stories.tsx
packages/components/src/combobox/ComboBox.tsx

The mouse interaction is a bit off, should work like this: https://sapui5.hana.ondemand.com/#/entity/sap.m.ComboBox/sample/sap.m.sample.ComboBox
When you've already selected a value and you click in the input field the previously selected value should be selected (markerat)
fix: #657 
- add a mouseUp handler
- add a test

fix(combobox): select the previous value on click

---

apps/docs/docs/components/grid.mdx
apps/docs/src/components/examples/grid/GridExamples.tsx

Typo 💟 
Changed two sizings on docweb

docs: typo on numbers in grid sizing table

---

packages/components/src/breadcrumbs/Breadcrumbs.stories.tsx
packages/components/src/breadcrumbs/Breadcrumbs.tsx
packages/components/src/breadcrumbs/index.ts

Component did not allow any custom styling.
- Extend react aria breadcrumbs
- Deprecate and rename prop type

fix(breadcrumbs): 💄 accept custom className

---

packages/components/src/button/Button.module.css
packages/components/src/link-button/LinkButton.module.css

DS-1205
When introducing medium and later small buttons, the current padding size does not scale well. This fixes the issue by reducing the large button left/right padding to 24px instead of 32.
change left/right padding on large button to `--size-100`
change left/right padding on large linkbutton to `--size-100`

Fix(button):  change large size button padding

---

packages/components/src/tag/Tag.module.css

Our tags have a bit too much white space between the label and the X button. This PR makes them shorter. Also discovered and fixed height issues.
add size tokens
change tagText right padding to` --size-10` when `dismissable`
change tagText top/bottom padding to `7px`
change button padding to `--size-20`
`max-height` does not account for border, which made our tags 34px high instead of 32. 
We need to use `7px` for top/bottom padding on tagText to get the right height, but it is the same in Figma so there is no escaping the ugliness

fix(tag): 📏 padding changes 

---

apps/docs/changelog/source/10.4.1.md
apps/docs/changelog/source/11.0.0.md
apps/docs/changelog/source/11.1.0.md
nx.json
packages/components/src/date-picker/DatePicker.stories.tsx
packages/components/src/date-picker/DatePicker.tsx
packages/components/src/date-picker/DatePickerPopover.tsx
packages/components/src/date-picker/DateRangePicker.tsx

Custom portal element (DatePicker container) would kick in after a re render in the component. Causing the popover to mount there instead of document.body
* remove the custom portal element and fall back to the default value (document.body)
* add changelog entries generated when bulding the docs

fix(date-picker): remove custom portal element

---

apps/docs/blog/release-notes/10.0.0.mdx
apps/docs/blog/release-notes/10.1.0.mdx
apps/docs/blog/release-notes/10.1.1.mdx
apps/docs/blog/release-notes/10.2.0.mdx
apps/docs/blog/release-notes/10.3.0.mdx
apps/docs/blog/release-notes/10.4.0.mdx
apps/docs/blog/release-notes/11.0.0.mdx
apps/docs/blog/release-notes/2.0.0.mdx
apps/docs/blog/release-notes/3.0.0.mdx
apps/docs/blog/release-notes/4.0.0.mdx
apps/docs/blog/release-notes/5.0.0.mdx
apps/docs/blog/release-notes/6.0.0.mdx
apps/docs/blog/release-notes/7.0.0.mdx
apps/docs/blog/release-notes/8.0.0.mdx
apps/docs/blog/release-notes/9.0.0.mdx
apps/docs/blog/release-notes/authors.yml

The docs dev server makes an annoying warning that recommends a global configuration for author data.
- Configure global authors
- Use global authors in old posts

docs: add authors map file and update all release notes

---

packages/components/src/dropdown/Dropdown.stories.tsx
packages/components/src/dropdown/Dropdown.tsx

The dropdown only has the vertical ellipsis icon. The horizontal one seems much more popular
Add custom icon support for Dropdown

feat(dropdown): add custom icon support

---

packages/components/.eslintrc.cjs
packages/components/src/breadcrumbs/Breadcrumbs.tsx
packages/components/src/combobox/ComboBox.tsx
packages/components/src/combobox/index.ts
packages/components/src/combobox/types.ts
packages/components/src/file-upload/DropZone.stories.tsx
packages/components/src/grid/Grid.tsx
packages/components/src/grid/GridItem.tsx
packages/components/src/grid/index.ts
packages/components/src/info-banner/InfoBanner.tsx
packages/components/src/select/index.ts
packages/components/src/select/types.ts
packages/components/src/table/Table.tsx
packages/components/src/tabs/Tabs.tsx
packages/components/src/theme/tokens.ts

This commit automates the ESLint versioning for the components package by converting the static .eslintrc.json to a dynamic .eslintrc.cjs file. The ESLint configuration now reads the package version directly from package.json, eliminating the need for manual updates.
Additionally, this commit removes several deprecated components, props, and types across the codebase to improve maintainability and adhere to the latest API standards. This includes:
- Breadcrumbs: Removed deprecated `BreadcrumbProps` type.
- ComboBox: Refactored `ComboBoxSelection` to `ComboBoxSection` and removed deprecated exports and types (`Item`, `Section`).
- Grid: Removed deprecated `Flex` export and `fluid` prop.
- GridItem: Removed deprecated `FlexItem` export and `col` prop.
- InfoBanner: Removed deprecated …

feat!: Automate ESLint versioning and remove deprecated features

---

packages/components/src/button/Button.stories.tsx
packages/components/src/link-button/LinkButton.stories.tsx
packages/components/src/table/Table.stories.tsx

The interaction test to size in button, linkButton, and tabel are working perfectly when it be change in display scaling—either browser zoom or OS display settings.
remove the size test from the components ( button, linkButton, and tabel) in storybook

test: remove size test from button linkButton and table

---

packages/components/src/button/Button.stories.tsx
packages/components/src/link-button/LinkButton.stories.tsx
packages/components/src/modal/Dialog.tsx
packages/components/src/theme/tokens.css
packages/components/src/theme/tokens.ts

`LinkButton` danger variant has color contrast violations in dark mode
- Revert "fix(theme): change dark mode values for danger button"
- test(link-button): remove a11y test bypass
- test(button): move interaction test to a separate story (because it interfered with a11y tests)

fix(link-button): replace background color for danger variant

---

packages/components/.storybook/main.ts
packages/components/project.json

Our Chromatic config dont like us running storybook process from within `packages/components`
A quick fix that configures Storybook different depending on the job

chore: create separate storybook configs for serve and build

---

packages/components/src/layout/components/SidebarLink.tsx

Support ticket, active state not showing properly in environments using a basepath other than `/`
add basepath to active link comparison
Tested in playground app with a different basepath, hard to test otherwise!

fix(layout): add basepath to active link comparison

---

packages/components/src/popover/Popover.module.css

Fixes this issue:
To look like:

fix(popover): prevent line breaks too early

---

apps/docs/src/css/custom.css

Unable to switch between dark/light mode in the docs app properly
- remove color-scheme import to global stylesheet
- remove duplicate font face at-rule

docs: remove color-scheme import to global stylesheet

---

.github/workflows/storybook-tests.yml

Dependabot is angry with us for not declaring permissions 
https://github.com/migrationsverket/midas/security/code-scanning/17
add missing permissions to workflow

ops: add missing permissions to workflow

---

.stylelintrc.json
packages/components/src/accordion/AccordionItem.module.css

AccordionItem has "extra" padding in the [docs app production build](https://designsystem.migrationsverket.se/components/accordion/)
Actually the correct padding is being overwritten by the default styles of the `Button` component due to the import order of CSS classes.
Read more here: https://github.com/facebook/docusaurus/issues/4518
- add a funky :not-selector to increase the specificity of the accordion item trigger button styles
Inspired by this post css plugin: https://github.com/MadLittleMods/postcss-increase-specificity
We could also do something like `button .triggerButton` to increase the specificity, or do `!important`. 
Is this a bigger issue?

fix(accordion): increase specificity for button css
