packages/radio/src/lib/Radio.module.css
=> fix(radio): change padding on label and helper text

apps/docs/docs/get-started/design/index.mdx
Fixade en XD-länk som inte går att kommentera och tog bort Figma-länken för det är ändå ingen annan som kan jobba med det i nuläget.
=> DS-388 Fix XD and Figma link

apps/docs/static/data/textarea.json, apps/docs/static/data/textfield.json, packages/textfield/src/lib/TextField.module.css
Always adjust text fields at bottom
=> fix(textfield): fix alignment

apps/docs/docs/components/checkbox.mdx, apps/docs/docs/components/radio.mdx, apps/docs/docs/components/select.mdx
Added guidelines on which component to choose
=> docs: add flowcharts to select, radio and checkbox

apps/docs/docs/intro.mdx
Added info about the current state of the docweb
=> docs(intro): add infobanner

apps/docs/docs/components/link.mdx
=> docs(link): change description, introduction and example. add flowchart

.github/workflows/components-ci.yml, .github/workflows/dependency-review.yml, .github/workflows/documentation-test-ci.yml, apps/docs/docs/components/spinner.mdx
=> docs(spinner): add use case and guidelines

apps/docs/docs/get-started/design/index.mdx
Funkade inte helt när jag testade lokalt. Det blir bara en "nedladdning" med samma storlek som xd-filen.
=> docs(design): add XD-file as a downloadable asset

apps/docs/docs/components/button.mdx, packages/button/src/lib/Button.module.css, packages/button/src/lib/ButtonGroup.module.css, packages/button/src/lib/ButtonGroup.stories.tsx, packages/button/src/lib/ButtonGroup.tsx, packages/button/src/lib/index.ts
=> feat(button): add buttongroup component, move mobile rules

apps/docs/docs/components/multi-select.mdx, packages/multi-select/src/lib/MultiSelect.tsx
Borde lösa problemet i docs utan att påverka funktionen i övrigt
=> Fix/DS-557 Multiselect renders incorrect in docweb

apps/docs/docs/components/multi-select.mdx, packages/multi-select/src/lib/MultiSelect.tsx
=> Docs/ds 642 MultiSelect

packages/components/README.md, packages/components/package.json
uppdaterat readme och package.json
=> Chore/ds 679 metadata för package

packages/components/src/select/Select.spec.tsx, packages/components/src/select/useMultiSelectState.ts
return a string for single select
=> fix(select): return a string from single select

packages/components/src/table/Table.spec.tsx, packages/components/src/table/Table.tsx
[Support ticket](https://jira.migrationsverket.se/browse/DS-751)
=> fix(table): preserve classNames when using props.className

packages/components/package.json
rätt ordning på grejerna för att tysta storybook
=> fix(theme): reorder theme export

apps/playground/src/app/app.tsx, packages/components/src/select/HiddenMultiSelect.tsx, packages/components/src/select/Select.module.css, packages/components/src/select/Select.spec.tsx, packages/components/src/select/Select.tsx, packages/components/src/select/useMultiSelectState.ts
Adds a hidden `<select>` element
Handles `errorMessage`, `isRequired`, `isInvalid` props
Adds tests for validation
=> fix(select): add isRequired validation

apps/docs/docs/get-started/use.mdx
Add UIkit 18 for XD
- Remove UI_kit_17.zip
- Add UI_kit_18.zip
- Change link to web view
=> docs: add new UIkit

packages/components/src/date-picker/DatePicker.module.css
=> fix(date-picker): change selected date color to blue150

package.json
Replace `husky install` with `husky`. Reference: https://github.com/typicode/husky/releases/tag/v9.0.1
=> chore: update husky prepare script

packages/components/src/table/Table.tsx
Write a deprecate comment that variant narrow will be deprecated
Add deprecated message 
=> fix(table): write a deprecate comment that narrow will be deprecate

packages/components/src/button/Button.tsx
Deprecate small size 
Add deprecate comment
=> fix(button): write a deprecate comment that size small will be deprecate

packages/components/src/layout/Layout.module.css, packages/components/src/layout/Layout.stories.tsx, packages/components/src/layout/components/Header.tsx, packages/components/src/layout/components/Sidebar.tsx, packages/components/src/logo/Logo.tsx
Fixed design adjustments from new new sketches
- Sidebar Footer is now Sidebar Header
=> fix(layout): design adjustments

packages/components/src/tooltip/Tooltip.module.css
=> refactor: add dark moode to tooltip

apps/docs/docs/dev/localization.mdx, apps/docs/src/components/examples/LocalizationExamples.tsx
One pager with developer docs for using localization features from Midas/React Aria
Add react examples + page on dev section
=> docs(localization): add dev instructions for localization

packages/components/src/date-field/DateField.module.css
=> refactor(date-field): use new tokens

packages/components/src/button/Button.module.css, packages/components/src/toast/Toast.module.css, packages/components/src/tooltip/Tooltip.module.css
=> refactor: fix token in button tooltip and toast

packages/components/src/calendar/Calendar.module.css, packages/components/src/textarea/TextArea.module.css
Getting ready for dark mode 🕶️ 
Update tokens for `calendar` 📆 and `text-area` ✍️
=> refactor: use new css tokens for `calendar` and `text-area`

packages/components/src/calendar/RangeCalendar.stories.tsx, packages/components/src/calendar/RangeCalendar.tsx, packages/components/src/calendar/index.ts, packages/components/src/date-picker/DatePicker.module.css, packages/components/src/date-picker/DatePicker.stories.tsx, packages/components/src/date-picker/DatePicker.tsx, packages/components/src/date-picker/DateRangePicker.stories.tsx
Dark mode adjustments and refactor RangeCalendar to new component
- Remove inputWrapper refs
- Some minor storybook refs
- Range Calendar refactor
=> refactor(date-picker): new tokens and style fixes to date-picker

.github/workflows/components-ci.yml, nx.json, package-lock.json, package.json, packages/components/.storybook/examples/Form.stories.tsx, packages/components/.stylelintrc.json, packages/components/project.json, packages/components/src/date-field/DateField.module.css, packages/components/src/link-button/LinkButton.spec.tsx, packages/components/src/link/Link.stories.tsx, packages/components/src/modal/Dialog.module.css, packages/components/src/modal/Dialog.stories.tsx, packages/components/src/select/Select.spec.tsx, packages/components/src/select/Select.tsx, packages/components/src/select/SelectListBox.tsx, packages/components/src/theme/tokens.css
Enables linting in packages/components
`nx lint components`, `nx stylelint components`
Add nx targets for eslint and stylelint
Take care of linting errors
=> chore(components): add linting

apps/docs/docs/get-started/contribute.mdx, apps/docs/docusaurus.config.ts
Add instructions to make sure release commits are merged and not rebased
- add some prism language to hightlight sh and css
- add instructions for release
- update workflow graph to reflect how it is happening IRL
- update styleguide with new token import
=> docs: release instructions

packages/components/src/button/Button.module.css, packages/components/src/layout/components/Sidebar.tsx
Wrong token icon in button icon
Change the token in button icon to icon primary  DS-870
Change the button variant to icon DS-852
=> fix: change button variant to icon

packages/components/src/accordion/AccordionItem.tsx, packages/components/src/calendar/Calendar.tsx, packages/components/src/calendar/RangeCalendar.tsx, packages/components/src/date-field/DateField.module.css, packages/components/src/date-field/DateField.tsx, packages/components/src/date-picker/DatePicker.module.css, packages/components/src/date-picker/DatePicker.tsx, packages/components/src/select/HiddenMultiSelect.tsx, packages/components/src/select/Select.tsx, packages/components/src/tabs/Tabs.tsx, packages/components/src/textfield/TextField.module.css, packages/components/src/textfield/TextField.tsx
Reverts migrationsverket/midas#362
=> Revert "fix: change to our typography"

apps/docs/docs/dev/dark-mode.mdx, apps/docs/docs/get-started/use.mdx
Adds version 20 of UI-kit, which now has a version for dark theme 
Add UI-kit 20
Remove Ui-kit 19
Update info on use.mdx
=> docs(docs): add new UI-kit

apps/docs/docs/components/badge.mdx, packages/components/src/badge/Badge.module.css, packages/components/src/badge/Badge.stories.tsx, packages/components/src/badge/Badge.tsx, packages/components/src/badge/BadgeContainer.tsx, packages/components/src/badge/index.ts, packages/components/src/index.ts
New component: Badge
Add new component Badge
New page on docweb
See storybook
=> feat(badge): 🆕 new component - badge to indicate user of unread items

packages/components/src/date-picker/DatePicker.module.css
Dividers in disabled has different color than place holder text  
https://github.com/migrationsverket/midas/issues/323
Add disabled style to segment
=> fix(date-picker): add disabled style to segment

apps/docs/docs/design-patterns/page-loading.mdx
Clarify when to use which loader to use
Added text and changed wording to page-loaders.mdx
=> docs(docs): add clarification on when to use which loader

apps/docs/docs/components/link.mdx, apps/docs/static/files/CHANGELOG.md
the url addresses are broken
- add the right url address
- remove unused code
=> docs(link): fix broken url address and remove unused code

packages/components/src/select/Select.stories.tsx
[This test](https://github.com/migrationsverket/midas/actions/runs/14220097482/job/39845737752) fails every now and then 
Assert input validity instead of dom elements rendered by state
We'll see if this does the trick
=> test(select): ✅ fix a flaky test

packages/components/src/combobox/ComboBox.module.css
the input has no background color 
DS-931
fix  background color token
=> fix(combobox): fix background color to input

packages/components/src/date-picker/DatePicker.module.css
The icon and border have wrong color in disabled.
Ref number DS-929
add disabled selector to inputfield and add color to icon in disabled selector 
=> fix(date-picker): add disabled selector to inputfield and add color to icon

apps/docs/docs/get-started/contribute.mdx
Update contribute page to reflect current status of release process
=> docs(contribute): update release process and general guidelines

apps/docs/docs/components/button.mdx, apps/docs/docs/design-patterns/buttons-and-links.mdx, apps/docs/src/css/custom.css, packages/components/src/button/Button.module.css
Remove live code examples
- fix(button): add cursor styling for disabled state
- docs: add margin to card and sibling code blocks
- docs(button): remove live code examples
=> docs(button): 📝 remove live code examples 

apps/docs/docs/components/badge.mdx
=> docs(badge): :memo: remove live code examples

apps/docs/docs/components/accordion.mdx, apps/docs/src/components/examples/accordion/AccordionExamples.tsx
Second go at updating accordion docs 🥈
=> docs: remove livecode and update accordion docs

apps/docs/docs/components/text.mdx, packages/components/src/text/Text.tsx
Enhance them docs
- Remove union type
- Remove live code examples
- Add form usage example
=> docs(text): 📝 remove live code and update documentation

packages/components/src/select/Select.stories.tsx
[Validation tests for select](https://github.com/migrationsverket/midas/actions/runs/14310062804/job/40102638079) keep on failing randomly
add await statements [playwright best practices](https://playwright.dev/docs/best-practices#dont-use-manual-assertions)
=> test(select): ✅ await assertions in flaky tests

apps/docs/docs/components/fileupload.mdx, apps/docs/src/components/examples/file-upload/FileUploadExamples.tsx
Improve them docs.
* Remove live code examples
* Add API table
* Add `allowsMultiple` example
* Add controlled example
=> docs(file-upload): remove live code block

apps/docs/docs/components/table.mdx, apps/docs/src/components/examples/table/TableExamples.tsx, packages/components/src/table/Table.tsx, packages/components/src/table/index.ts
Improved documentation
- add prop comment
- export everything from table
- add examples
- remove live code
=> docs(table): 📝 remove live code and update documentation

apps/docs/docs/components/tooltip.mdx, apps/docs/src/components/examples/tooltip/TooltipExamples.tsx, apps/docs/src/components/propsTable.tsx, apps/docs/src/css/propstable.module.css, package-lock.json, package.json
Update Tooltip documentation
- remove livecode and add a bunch of examples
- update propstable a bit (still not perfect but better)
=> docs(tooltip): update tooltip documentation 🧰 🔧 🔨 

apps/docs/docs/components/tabs.mdx, packages/components/src/tabs/Tabs.tsx
Improve them docs
* Remove live code examples
* Add examples on usage
* Edit prop comments
=> docs(tabs): 📝 remove live code and update documentation

apps/docs/docs/components/skeleton.mdx
=> docs(skeleton): remove live code block

apps/docs/docs/components/spinner.mdx
=> docs(spinner): remove live code block

apps/docs/docs/components/progress-bar.mdx
improve docs
remove the lic´ve code block
=> docs(progress-bar): remove live code block

apps/docs/docs/components/heading.mdx, packages/components/src/heading/Heading.tsx
=> docs(heading): remove live code block

packages/components/src/calendar/Calendar.module.css, packages/components/src/calendar/Calendar.tsx, packages/components/src/calendar/RangeCalendar.tsx, packages/components/src/heading/Heading.module.css, packages/components/src/modal/Dialog.module.css, packages/components/src/modal/Dialog.stories.tsx, packages/components/src/modal/Dialog.tsx
There is a margin between heading and other component
add margin top to heading css file
=> refactor(heading): add margin block in css file

apps/docs/docs/components/spinner.mdx, packages/components/src/spinner/Spinner.stories.tsx, packages/components/src/spinner/Spinner.tsx
the name of prop _dark_ is not suitable 
change the name to _isOnColor_ 
=> refactor(spinner): change prop name

apps/docs/docs/components/logo.mdx
=> docs(logo): remove live code block

apps/docs/docs/components/search-field.mdx
=> docs(search-field): remove the live code block

apps/docs/docs/components/info-banner.mdx, apps/docs/docs/components/tabs.mdx, apps/docs/src/components/examples/tabs/TabsExamples.tsx, packages/components/src/tabs/Tabs.stories.tsx, packages/components/src/tabs/Tabs.tsx, packages/components/src/tabs/index.ts, packages/components/src/theme/tokens.ts, packages/components/src/utils/useObserveElement.tsx
* Supports controlled mode 
* Changes aria-orientation on window resize 
* Supports tabs with same word in different casing
* Doesn't throw an error when misconfigured
- refactor: extend react aria `Tabs` and (almost all) it's props
- docs: add controlled example
=> refactor(tabs) ♻️📝

apps/docs/docs/components/date-picker.mdx, apps/docs/src/components/examples/date-picker/DatePickerExamples.tsx, apps/docs/src/css/propstable.module.css
Remove LiveCode, add some more examples
- fix propstable css bug
- remove live code
- add examples and descriptions
=> docs(datepicker): update documentation

apps/docs/docs/components/radio.mdx, apps/docs/src/components/examples/radio/RadioExamples.tsx
improve docs
remove the live code block and create a file for example
**its need to add information  about control mode**
=> docs(radio): remove live code block and create a file for example

apps/docs/docs/components/datefield.mdx, apps/docs/src/components/examples/date-field/DateFieldExamples.tsx
=> docs(date-field): update documentation 📅 

apps/docs/docs/components/checkbox.mdx, apps/docs/src/components/examples/checkbox/CheckboxExamples.tsx
improve docs
remove live code block and add control mode
**its need to add information  about control mode**
=> docs(checkbox): remove live code block and add control mode

apps/docs/docs/components/combobox.mdx, apps/docs/src/components/examples/combobox/ComboboxExamples.tsx
improve docs
remove live code block and add controlled mode
=> docs(combobox): remove live code block and add controlled mode

apps/docs/docs/components/dropdown.mdx
Just remove live code, no other docs/code updates
➖ live code
This is not a 1:1 representation of React Aria Menu and the name is a bit confusing. Will be refactored in another ticket!
=> docs(dropdown): remove livecode from documentation 🔽 

apps/docs/docs/components/grid.mdx, apps/docs/src/components/examples/grid/GridExamples.tsx
Remove live code and replace card example with just colored boxes
=> docs(grid): remove livecode from documentation

apps/docs/docs/components/flex.mdx, apps/docs/src/components/examples/flex/FlexExamples.tsx
improve docs
remove live code block
=> docs(flex): remove live code block

apps/docs/docs/components/layout.mdx, apps/docs/src/components/examples/layout/LayoutExamples.tsx
Improve the documentation
I just removed the live code examples
Could be improved further, positions of the navigation is a bit wonky, separate issue in backlog
=> docs(layout): remove live code examples

apps/docs/docs/components/calendar.mdx, apps/docs/src/components/examples/calendar/CalendarExamples.tsx, packages/components/src/calendar/Calendar.module.css
Update calendar docs
- remove live code and add range example
- fix style in range-calendar where it was unclear which range was selected due to selection-end taking over
=> docs(calendar): update docs

apps/docs/docs/design-patterns/page-loading.mdx, apps/docs/static/templates/component-docs.mdx.hbs
Improved documentation.
- docs: remove live code from template
- docs: remove live code from loading indicator page
=> docs: remove live code

apps/docs/docs/components/textfield.mdx
Improved docs
- Remove a little live code example in textfield docs
=> docs(textfield): remove live code example

apps/docs/docs/components/textarea.mdx
Improved documentation.
- Remove live code example
=> docs(textfield): remove live code example from textarea

apps/docs/docs/components/card.mdx, apps/docs/src/components/examples/card/CardExamples.tsx
=> docs(card): remove the live code block

apps/docs/docs/get-started/use.mdx
Adds new version of XD UI-kit
Added MIDAS_UIkit_21.zip
Removed MIDAS_UIkit_20.zip
Updated links to online version
=>  Add new UI-kit

packages/components/src/theme/tokens.css, packages/components/src/theme/tokens.ts
box-shadow in focus state in checkbox component not correct in dark mode
_issue number: DS-999_
Add dark mode to focus in token.css file
=> fix(theme): add to focus dark mode

packages/components/src/tooltip/Tooltip.module.css, packages/components/src/tooltip/Tooltip.stories.tsx, packages/components/src/tooltip/Tooltip.tsx
Use react aria placement prop
_Issue number: DS-986_
change custom placement prop to react aria placement prop
=> feat(tooltip): change custom placement prop to react aria placement prop

apps/docs/docs/dev/forms.mdx, apps/docs/src/components/examples/form/FormExamples.module.css, apps/docs/src/components/examples/form/FormExamples.tsx, apps/docs/tsconfig.json
Utvecklarinstruktioner för formulär mer generellt som saknades på enskilda komponenter
=> docs(forms): boilerplate docs

apps/docs/docs/basics/tokens.mdx, apps/docs/static/files/CHANGELOG.md, packages/components/src/layout/Layout.module.css, packages/components/src/theme/tokens.css, packages/components/src/theme/tokens.ts
New fresh colors ✨
- Change background 
- Add tokens
- Update docs
=> feat(layout): ✨ change background color for menu item

packages/components/src/layout/Layout.module.css
=> feat(layout): change font weight for active menu item

packages/components/src/accordion/Accordion.module.css
Differens i öppen och stängd uncontained accordion
Ta dän utfyllnaden i det sista itemet
=> fix(accordion): 🐛 remove padding for last uncontained AccordionItem

.github/workflows/release.yml
When we've created a release from main we want to update the dev branch with the version commit
- update release script
=> chore: update release workflow to merge main into dev

package-lock.json, package.json, packages/components/src/calendar/RangeCalendar.stories.tsx
Our tests started failing 29/4
Mock the date in range calendar tests
Interesting behaviour, might be a bug? Or just a bad test probably, mock the date now and investigate further
=> test(calendar): mock date in range calendar tests

packages/components/src/select/Select.module.css, packages/components/src/select/Select.tsx
=> fix(select): add disabled styling to description

packages/components/src/combobox/ComboBox.module.css
in disabled state the icon is not disabled
_issue number: DS-1084_
add color in disabled state.
=> fix(combobox): add disabled color to the icon in disabled state

packages/components/src/modal/Dialog.module.css, packages/components/src/modal/Dialog.stories.tsx
Add z-index to modal header to prevent content from scrolling above it
- z-index fix
- New story with a lot of content forcing the modal to scroll
- support ticket
=> fix(modal): adjust modal header when content is scollable

packages/components/src/calendar/Calendar.module.css, packages/components/src/combobox/ComboBox.module.css, packages/components/src/date-picker/DatePicker.module.css, packages/components/src/select/Select.module.css, packages/components/src/theme/tokens.css
Change to new dialog style on DatePicker, Select and Combobox
- New dialog style DatePicker
- New dialog style Select
- New dialog style Combobox
- Adjust spacing on Calendar to match Figma
=> New Dialog Style

packages/components/src/theme/tokens.css, packages/components/src/theme/tokens.ts
use --support-border-warning instead of border-invalid
issue number: DS-1073
add deprecate to border-invalid
=> refactor(theme): deprecate border invalid

packages/components/src/toast/Toast.stories.tsx
Fix height of local example on storybook so we see the toasts :)
=> docs(toast): fix local example in storybook

packages/components/src/grid/Grid.tsx, packages/components/src/grid/GridItem.tsx
Prevent Midas classNames from getting overwritten
=> fix(grid): prevent midas classnames to get overwritten

packages/components/.eslintrc.json
=> chore: update version in eslint config

apps/docs/src/components/getComponentMetaData.tsx
- fixes no working storybook link from docs
=> build(docs): sets storybook url for main when no branch found

apps/docs/static/files/CHANGELOG.md, packages/components/src/common/types.ts, packages/components/src/date-field/DateField.module.css, packages/components/src/date-field/DateField.stories.tsx, packages/components/src/date-field/DateField.tsx, packages/components/src/textfield/TextField.module.css, packages/components/src/textfield/TextField.stories.tsx, packages/components/src/textfield/TextFieldBase.tsx, packages/components/src/theme/tokens.css
For use in internal systems
- Add a common type for components using the size property
- Add a story
- Edit the textfield css to use height instead of padding
=> feat(date-field): ✨ medium size

.github/workflows/publish.yml, packages/components/package.json
Increase supply-chain security
[Generating provenance statements
](https://docs.npmjs.com/generating-provenance-statements)
- Flip the provenance flag
- Update package.json according to [npm documentation](https://docs.npmjs.com/cli/v11/configuring-npm/package-json#repository)
=> chore: 👷 add npm provenance flag

packages/components/src/combobox/ComboBox.module.css, packages/components/src/combobox/ComboBox.stories.tsx, packages/components/src/combobox/ComboBox.tsx
For use in internal systems
- Add size prop
- Rename className for consistency
=> feat(combobox): ✨ medium size

packages/components/src/search-field/SearchField.module.css, packages/components/src/search-field/SearchField.stories.tsx, packages/components/src/search-field/SearchField.tsx
For use in internal systems
- Add size prop
=> feat(search-field): ✨ medium size

packages/components/src/button/Button.module.css, packages/components/src/button/Button.stories.tsx, packages/components/src/button/Button.tsx
Medium size to button component
Add new prop "size"
Add new class for style midum
Add a story
=> feat(button): add size property, a story and style

packages/components/src/select/Select.module.css, packages/components/src/select/Select.stories.tsx, packages/components/src/select/Select.tsx
Medium size Select
- Add new prop "size"
- Add new class for style midum
- Add a story 
- Add test
=> ✨ Feature/ds 1110 medium size select

apps/docs/docs/components/skeleton.mdx, packages/components/src/skeleton/Skeleton.stories.tsx, packages/components/src/skeleton/Skeleton.tsx
fix skeleton props, docs 
_issue number:DS-1092_
deprecate and add new variant
change the value from string to boolean to animation in docs
add tests
=> :skull: Refactor/skeleton

packages/components/src/accordion/Accordion.module.css, packages/components/src/button/Button.module.css, packages/components/src/calendar/CalendarHeader.tsx, packages/components/src/layout/Layout.stories.tsx, packages/components/src/search-field/SearchField.module.css, packages/components/src/search-field/SearchField.tsx
Pixel pushing the Button component and using the 'medium' size in internal components
=> chore: Button pixel pushing

packages/components/src/accordion/Accordion.stories.tsx, packages/components/src/calendar/Calendar.stories.tsx, packages/components/src/calendar/RangeCalendar.stories.tsx, packages/components/src/checkbox/Checkbox.stories.tsx, packages/components/src/combobox/ComboBox.stories.tsx, packages/components/src/date-picker/DatePicker.stories.tsx, packages/components/src/file-upload/FileUpload.stories.tsx, packages/components/src/radio/Radio.stories.tsx, packages/components/src/select/Select.stories.tsx, packages/components/src/tabs/Tabs.stories.tsx, packages/components/src/textfield/TextArea.stories.tsx, packages/components/src/textfield/TextField.stories.tsx
Chromatic takes snapshots of duplicate component states
- remove duplicates
=> chore: disable chromatic snapshots for duplicate states

apps/docs/blog/releases/10.0.0/index.mdx
Additional release notes. Add more stuff here if something is missing!
=> docs(release): update release notes with info on medium size components

packages/components/src/select/Select.module.css
Increase the space between tag group and select
Add to margin top 0.5rem
=> fix(select): increase the margin top to give more space between tag group and select

apps/docs/blog/releases/8.0.0/index.mdx, apps/docs/blog/releases/9.0.0/index.mdx
We forgot to mention (and make a major release) breaking changes for `Card`
- update migration guides
=> docs: add migration guide for v8.3.0

packages/components/src/layout/Layout.tsx
A fellow co-worker reported the lack of documentation on this prop
- update docs on clientSideHref prop
=> docs(layout): update docs on clientSideHref prop

apps/docs/babel.config.js, package-lock.json, package.json, packages/components/src/select/SectionedListLayout.ts, packages/components/src/select/Select.module.css, packages/components/src/select/Select.stories.tsx, packages/components/src/select/Select.tsx, packages/components/src/select/SelectListBox.tsx
A performance fix with a Virtualizer component around the ListBox
* feat(select): allow for option id to be string or number
* feat(select): use midas checkbox
* fix(select): virtualize the scroll box
Please see if you can breake it!
=> fix(select): virtualize listbox

packages/components/src/link-button/LinkButton.stories.tsx
Remove the story icon from the storybook
Delete the story
=> chore(link-button): remove the story icon from the storybook

packages/components/src/theme/tokens.css
invalid token value
change the value  from --blue-140 to --blue-130
=> fix: fix invalid token value

packages/components/src/date-picker/DatePicker.module.css
Fixar att dubbel border ibland renderas om knappen inte blir exakt lika hög som fältet
Tagit bort border från knapp och låter enbart fältet lägga till border undertill
=> fix(date-picker): fix height issue with button in field

apps/docs/docs/components/link.mdx, packages/components/src/card/Card.tsx, packages/components/src/link-button/LinkButton.tsx, packages/components/src/link/Link.stories.tsx, packages/components/src/link/Link.tsx
- Added external link and download icons based on `<Link />` usage
- Added JSDocs on "as"-props
=> fix(link): better icon logic on links, support for external and download

packages/components/src/calendar/Calendar.module.css, packages/components/src/calendar/Calendar.stories.tsx, packages/components/src/calendar/Calendar.tsx, packages/components/src/calendar/CalendarHeader.tsx, packages/components/src/calendar/RangeCalendar.tsx
=> feat(calendar): extend calendar with state for disabled

.github/workflows/test-storybook.yml
We're out of Chromatic snaps
Add our old test storybook workflow to run component tests
=> chore: run storybook tests in pipeline temporary

apps/docs/docs/get-started/use.mdx
Adds UI kit version 24 for XD 
Updated download link (and fixed unwanted line break)
Added MIDAS_Uikit_24.zip
Removed old zips
=> Add new UI kit

packages/components/src/grid/Grid.stories.tsx
We bypass a11y testing in `Grid` stories
Remove the bypass
Not needed anymore
=> test(grid): remove a11y test bypass

apps/docs/docs/components/select.mdx, apps/docs/src/components/examples/select/SelectExamples.tsx
Some confusion on how to use controlled selection in the single select mode.
- add docs
=> docs(select): add docs on controlled selection for single select

packages/components/src/search-field/SearchField.module.css, packages/components/src/search-field/SearchField.stories.tsx, packages/components/src/search-field/SearchField.tsx
Component did not accept custom styling via className
- add custom className support
- change color of input text
- change size of clear button
=> fix(search-field): 💄 accept custom className

packages/components/src/layout/Layout.stories.tsx, packages/components/src/layout/Layout.tsx
Component did not accept custom styling via className
- add custom className support
=> fix(layout): 💄 accept custom className

packages/components/src/color-scheme-switch/ColorSchemeSwitch.stories.tsx, packages/components/src/color-scheme-switch/ColorSchemeSwitch.tsx
Component doesnt accept custom styling via className
- add custom className support
=> fix(color-scheme-switch): 💄 accept custom className

packages/components/src/calendar/Calendar.module.css, packages/components/src/calendar/CalendarGrid.tsx, packages/components/src/calendar/RangeCalendar.stories.tsx, packages/components/src/calendar/RangeCalendar.tsx, packages/components/src/theme/tokens.css, packages/components/src/theme/tokens.ts
- Days inside range has new style
- New tokens 
- New story to display a calendar range with selected dates
[https://designsystem.migrationsverket.se/pr-preview/pr-693/storybook/?path=/story/components-calendar-rangecalendar--selected-dates](https://designsystem.migrationsverket.se/pr-preview/pr-693/storybook/?path=/story/components-calendar-rangecalendar--selected-dates)
=> fix(calendar): add style for dates in range

apps/docs/src/css/index.module.css, apps/docs/src/pages/index.tsx
Start page content was not staying in place on page load
Remove "browser only" solution and fix issue with css
https://github.com/user-attachments/assets/34bbcab4-5835-461d-a8c6-2064eff7a97e
=> docs: fix strange start page render on load

packages/components/src/link/Link.tsx
Fixes #710 
Passed prop `target` on to `Component`
=> fix(link): 🔧 fix issue with Link not opening in new window when target='_blank'

packages/components/src/layout/Layout.module.css
remove the background color.
issue number: _DS-1276_
delete the background color from class main and app
=> style: remove background color from class main and app

packages/components/src/list-box/ListBox.module.css, packages/components/src/theme/tokens.css, packages/components/src/theme/tokens.ts
Adjusts the styling of the section headers in the Select and Combobox components. 
- Sets the text color to `--blue-120`.
- Adjusts the padding to have `0.75rem` on the start side.
=> feat(listbox)

packages/components/src/grid/index.ts
Support ticket
* add export for GridProps type
=> fix(grid): add export for GridProps type

packages/components/.storybook/modes.ts, packages/components/.storybook/preview.tsx, packages/components/src/button/Button.stories.tsx, packages/components/src/combobox/ComboBox.stories.tsx, packages/components/src/date-field/DateField.stories.tsx, packages/components/src/date-picker/DatePicker.stories.tsx, packages/components/src/date-picker/DateRangePicker.stories.tsx, packages/components/src/link-button/LinkButton.stories.tsx, packages/components/src/search-field/SearchField.stories.tsx, packages/components/src/select/Select.stories.tsx, packages/components/src/table/Table.stories.tsx, packages/components/src/textfield/TextField.stories.tsx
Remove the size from global in storybook
Delete the sizeMode
Delete size from preview
Delete global size from components storybook and adjust it
=> chore: remove size from global, and adjust the storybook in button

packages/components/src/search-field/SearchField.stories.tsx
remove size global 
delete the global size and fix the test
=> test(search-field): remove size global and fix the test to size

packages/components/src/badge/Badge.module.css, packages/components/src/badge/Badge.stories.tsx, packages/components/src/theme/tokens.css, packages/components/src/theme/tokens.ts
The label and background has contrast issues
* Use new color token
* run a11y tests for `Badge` in pipeline
=> fix(badge): replace label color

packages/components/src/select/Select.tsx, packages/components/src/table/Table.stories.tsx, packages/components/src/tag/Tag.stories.tsx
Friday housekeeping, noisy tests
- **test(tag): add textValue to mute console.warn**
- **fix(select): add aria label to checkbox**
- **test(table): remove flaky test**
=> test: mute console warnings

packages/components/src/layout/Layout.stories.tsx, packages/components/src/layout/components/SkipLink.tsx
Skip to content link not working
remove hash from main role querySelector
=> fix(layout): remove hash from main role querySelector

apps/docs/docs/get-started/contribute/coding.mdx, apps/docs/docs/get-started/contribute/tests.mdx
New branch strategy, new release procedure -> new dev instructions
=> docs: update developer instructions

apps/docs/src/components/examples/tanstack-table/TanstackTableExamples.tsx, packages/theme/vite.config.ts
@midas-ds/theme has no readme 
add README and CHANGELOG md files to build
=> fix(theme): add README and CHANGELOG to build

nx.json, packages/datepicker-styles/.eslintrc.json, packages/datepicker-styles/README.md, packages/datepicker-styles/jest.config.ts, packages/datepicker-styles/package.json, packages/datepicker-styles/project.json, packages/datepicker-styles/src/lib/react-datepicker.css, packages/datepicker-styles/tsconfig.json, packages/datepicker-styles/tsconfig.lib.json, packages/datepicker-styles/vite.config.ts, tsconfig.base.json
custom midas styles for `react-datepicker` added to publishable package
=> feat(datepicker-styles): add package datepicker-styles

.verdaccio/config.yml, packages/components/package.json, packages/datepicker-styles/package.json, packages/table-styles/package.json, packages/theme/package.json, project.json, tools/release-local/.eslintrc.json, tools/release-local/README.md, tools/release-local/executors.json, tools/release-local/package.json, tools/release-local/project.json, tools/release-local/src/executors/release-local.ts, tools/release-local/src/executors/schema.d.ts, tools/release-local/src/executors/schema.json, tools/release-local/tsconfig.json, tools/release-local/tsconfig.lib.json, tsconfig.base.json
```
nx run @midas-ds/source:release:local
```
=> test(integration): setup verdaccio

package-lock.json, package.json
NX  Falling back to ts-node for local typescript execution. This may be a little slower. - To fix this, ensure @swc-node/register and @swc/core have been installed
=> chore: add swc dependencies

.github/workflows/pr-checks.yml
We dont always need to install playwright in the PR-checks workflow
get affected projects before installing playwright
=> ops: add condition to playwright installation step
